name: arc-test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-lab-runners
    steps:
      - name: Show info
        run: |
          echo "rodando no ARC"
          hostname
          uname -a
          sleep 30
